create table "public"."plants" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "room" text not null
);


alter table "public"."plants" enable row level security;

create table "public"."watering_history" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "plant" bigint not null
);


alter table "public"."watering_history" enable row level security;

CREATE UNIQUE INDEX plants_pkey ON public.plants USING btree (id);

CREATE UNIQUE INDEX watering_history_pkey ON public.watering_history USING btree (id);

alter table "public"."plants" add constraint "plants_pkey" PRIMARY KEY using index "plants_pkey";

alter table "public"."watering_history" add constraint "watering_history_pkey" PRIMARY KEY using index "watering_history_pkey";

alter table "public"."watering_history" add constraint "watering_history_plant_fkey" FOREIGN KEY (plant) REFERENCES plants(id) ON DELETE CASCADE not valid;

alter table "public"."watering_history" validate constraint "watering_history_plant_fkey";

create policy "everyone can select"
on "public"."plants"
as permissive
for select
to public
using (true);


create policy "everyone can select"
on "public"."watering_history"
as permissive
for select
to public
using (true);



